name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate:up
        npm run test -- -i
      env:
        CI: true
        DBHOST_TEST: ${{ secrets.DBHOST_TEST }}
        DBUSER_TEST: ${{ secrets.DBUSER_TEST }}
        DBNAME_TEST: ${{ secrets.DBNAME_TEST }}
        DBPASS_TEST: ${{ secrets.DBPASS_TEST }}
        DBPORT_TEST: ${{ secrets.DBPORT_TEST }}
        DBHOST: ${{ secrets.DBHOST_TEST }}
        DBUSER: ${{ secrets.DBUSER_TEST }}
        DBNAME: ${{ secrets.DBNAME_TEST }}
        DBPASS: ${{ secrets.DBPASS_TEST }}
        DBPORT: ${{ secrets.DBPORT_TEST }}
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE }}
