name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate:up
        npm run test -- -i
      env:
        CI: true
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE }}
